name: Trigger auto deployment for nlp-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ prod ]
    paths:
    - '**'
    - '.github/workflows/nlp-service-AutoDeployTrigger-5d52c092-17f9-44d6-9476-27e904736cac.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NLPSERVICE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: rumorzcontainers.azurecr.io
          registryUsername: ${{ secrets.NLPSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NLPSERVICE_REGISTRY_PASSWORD }}
          containerAppName: nlp-service
          resourceGroup: rumorz-app-prod
          imageToBuild: rumorzcontainers.azurecr.io/nlp-service:${{ github.sha }}
          
            

     

